# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Affk58F5CZFLLu00NjO1-CBU8D29lhYJ
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.figure(figsize=(6, 5))
plt.plot(x, y, color='blue')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x_random = np.random.uniform(0, 10, 50)
y_random = np.random.uniform(0, 10, 50)
plt.figure(figsize=(6, 5))
plt.scatter(x_random, y_random, color='blue')
plt.show()

import pandas as pd
mb = pd.read_csv('WHO COVID-19 cases.csv')
filtr=mb[mb['Country']=='Afghanistan']
print(filtr)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread('rasm1.jpg')
rasm2=cv2.imread('rasm2.jpg')
rasm3=cv2.imread('rasm3.jpg')
rasm4=cv2.imread('rasm4.jpg')
cv2_imshow(rasm1)
cv2_imshow(rasm2)
cv2_imshow(rasm3)
cv2_imshow(rasm4)

oqqora1=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
oqqora2=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
oqqora3=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
oqqora4=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora1)
cv2_imshow(oqqora2)
cv2_imshow(oqqora3)
cv2_imshow(oqqora4)